syntax on
set number
set enc=utf-8
set ts=4
set sw=4
set sta
set smartindent
set et
set smartcase
set hlsearch
set ff=unix
set ffs=unix
set nobk
set nowb
set noswf
set list
set listchars=eol:$,tab:->,trail:·,extends:>,precedes:<,nbsp:·
colorscheme dhln
set wildmode=longest,list
set wildmenu
set t_Co=16
set background=dark
set relativenumber
set cursorline
map <Return> i<Return><Esc>^

" PHP Documentator
source ~/.vim/plugins/php-doc.vim
source ~/.vim/plugins/emmet.vim
inoremap <C-P> <ESC>:call PhpDocSingle()<CR>i 
nnoremap <C-P> :call PhpDocSingle()<CR> 
vnoremap <C-P> :call PhpDocRange()<CR>
let g:pdv_cfg_Type      = "mixed"
let g:pdv_cfg_Package   = ""
let g:pdv_cfg_Version   = ""
let g:pdv_cfg_Author    = "Albert Dahlin <info@albertdahlin.com>"
let g:pdv_cfg_Copyright = "Copyright (C) 2016 Albert Dahlin"
let g:pdv_cfg_License   = "GNU GPL v3.0 <http://www.gnu.org/licenses/gpl-3.0.html>"

if filereadable($HOME . "/.vim/localrc.vim")
    source $HOME/.vim/localrc.vim
endif
cabbrev E Explore

function! AlignEqualsRange() range
    let lineStart   = line("'<")
    let lineEnd     = line("'>")
    let equalsCol   = 0

    for i in range(lineStart, lineEnd)
        let col = stridx(getline(i), "=")
        if col > equalsCol
            let equalsCol = col
        endif
    endfor

    if &tabstop > 0
        let equalsCol += (&tabstop - (equalsCol % &tabstop)) % &tabstop
    endif

    for i in range(lineStart, lineEnd)
        let lineString      = getline(i)
        let col             = stridx(lineString, "=")
        let spaces          = equalsCol - col
        let lineStringEnd   = strpart(lineString, col)
        let lineString      = strpart(lineString, 0, col)
        let j               = 0
        while j < spaces
            let lineString .= " "
            let j += 1
        endwhile
        let lineString .= lineStringEnd
        call setline(i, lineString)
    endfor
endfunction

vnoremap <Leader>l :call AlignEqualsRange()<CR>
nnoremap <Leader>f mkHmt:%!elm-format --stdin<CR>'tzt'k
vnoremap <Leader>f :!elm-format --stdin<CR>

autocmd FileType php set keywordprg=~/.vim/plugins/php-doc
au BufReadPost,BufNewFile source ~/.vim/syntax/c.vim
